# Generated by Django 3.2.25 on 2025-06-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0044_consumption_wo_mtrl_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='auto_flag',
            field=models.BooleanField(default=False),
        ),
    ]
