# Generated by Django 3.2.25 on 2025-06-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0045_record_auto_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='auto_flag',
            field=models.BooleanField(default=False),
        ),
    ]
