# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181210_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_setting',
            name='page_number',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='project_setting',
            name='shot',
            field=models.FileField(default='', upload_to='uploads/profile'),
            preserve_default=False,
        ),
    ]
