# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20181212_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_setting',
            name='shot',
            field=models.FileField(blank=True, null=True, upload_to='uploads/profile'),
        ),
    ]
