# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20181212_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_setting',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
