# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20181212_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_setting',
            name='shot',
        ),
    ]
