# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='test_data',
            field=models.BooleanField(default=False),
        ),
    ]
