# Generated by Django 3.0 on 2022-11-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20190212_1129'),
        ('bugs', '0002_auto_20190123_1643'),
    ]

    operations = [
    ]
