# Generated by Django 3.2.25 on 2024-09-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_alter_itemcategory_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
