# Generated by Django 3.2.25 on 2024-09-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_alter_itemcategory_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_family', to='inventory.itemfamily'),
        ),
    ]
