# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shot',
            field=models.FileField(blank=True, null=True, upload_to='uploads/profile'),
        ),
    ]
