# Generated by Django 3.2.25 on 2025-06-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0032_alter_asset_label_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='device_series',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
