# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-23 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
        ('bases', '0002_auto_20190123_1643'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_reply',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem_reply',
            name='problem_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='problems.Problem'),
        ),
        migrations.AddField(
            model_name='problem_reply',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem_attachment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_files', to='problems.Problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='belong_to_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_formtype', to='bases.FormType'),
        ),
        migrations.AddField(
            model_name='problem',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='problem_create_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_super', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='problem',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='problem_update_at', to=settings.AUTH_USER_MODEL),
        ),
    ]
