# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('bases', '0002_auto_20181210_1616'),
        ('bugs', '0002_bug_belong_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bug_create_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bug',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bus_level', to='requests.Level'),
        ),
        migrations.AddField(
            model_name='bug',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_project', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bug_status', to='bases.Status'),
        ),
        migrations.AddField(
            model_name='bug',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bug_update_at', to=settings.AUTH_USER_MODEL),
        ),
    ]
