# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tester_result', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test_result_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_result', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_item', to='tests.Request_test_item')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_detail', to='tests.Test_result')),
            ],
        ),
        migrations.RemoveField(
            model_name='request_test_result',
            name='item',
        ),
        migrations.RemoveField(
            model_name='request_test_result',
            name='tester',
        ),
        migrations.DeleteModel(
            name='Request_test_result',
        ),
    ]
