# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_result_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_test',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_test', to='requests.Request'),
        ),
    ]
