# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20190212_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_test',
            name='owner',
        ),
    ]
