# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_remove_request_test_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_test_item',
            name='item',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
