# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20181210_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
