# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-23 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_auto_20190122_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='estimate_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
