# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-23 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_auto_20190123_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='estimate_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
